'use client';
import {useState} from 'react';
import {ArrowRight,LoaderCircle,Eye,EyeOff} from 'lucide-react';
type Mode='login'|'signup'|'forgot'|'reset';
export default function AuthForm({mode,next,configured,message}:{mode:Mode;next:string;configured:boolean;message?:string}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(message||'');
 const label={login:'Sign in',signup:'Create account',forgot:'Send reset link',reset:'Save new password'}[mode];
 async function submit(action:string){if(busy)return;setError('');setNotice('');if(['signup','reset'].includes(action)&&password!==confirmation){setError('Your passwords don’t match.');return;}setBusy(action);try{const r=await fetch('/api/auth/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email||undefined,password:password||undefined,next})});const data=await r.json() as {error?:string;redirect?:string;message?:string};if(!r.ok)throw Error(data.error||'Please try again.');if(data.redirect){window.location.assign(data.redirect);return;}setNotice(data.message||'Check your email for the next step.');setPassword('');setConfirmation('');}catch(e){setError(e instanceof Error?e.message:'Could not connect. Please try again.');}finally{setBusy('');}}
 return <>{!configured&&<p className="pa-notice" role="status">Account setup is in progress. Email and Google sign-in will be available once connected.</p>}{notice&&<p className="pa-notice" role="status">{notice}</p>}{error&&<p className="pa-error" role="alert">{error}</p>}{(mode==='login'||mode==='signup')&&<><button className="pa-google" disabled={!configured||!!busy} onClick={()=>submit('google')}><span aria-hidden="true">G</span>Continue with Google{busy==='google'&&<LoaderCircle className="spin" size={16}/>}</button><div className="pa-or"><span/>or use email<span/></div></>}<form onSubmit={e=>{e.preventDefault();void submit(mode)}}>{mode!=='reset'&&<label>Email address<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" disabled={!!busy}/></label>}{mode!=='forgot'&&<><label>{mode==='reset'?'New password':'Password'}<div className="pa-password"><input type={visible?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?1:12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} disabled={!!busy}/><button type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{mode!=='login'&&<><small>Use at least 12 characters.</small><label>Confirm password<input type={visible?'text':'password'} autoComplete="new-password" required value={confirmation} onChange={e=>setConfirmation(e.target.value)} disabled={!!busy}/></label></>}{mode==='login'&&<a className="pa-forgot" href="/forgot-password">Forgot password?</a>}</>}<button className="pa-primary" type="submit" disabled={!configured||!!busy}>{busy===mode?<LoaderCircle size={17} className="spin"/>:label}<ArrowRight size={17}/></button></form><p className="pa-switch">{mode==='login'?<>New to Pinkiri? <a href={'/signup?next='+encodeURIComponent(next)}>Create an account</a></>:mode==='signup'?<>Already have an account? <a href={'/login?next='+encodeURIComponent(next)}>Sign in</a></>:<a href={'/login?next='+encodeURIComponent(next)}>Back to sign in</a>}</p></>;
}
