"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,FileText,MessageSquare,Activity,Send,Check,Copy,Download,Search,LoaderCircle,PenLine,Calendar as CalendarIcon,Sparkles,ShieldAlert,ThumbsUp,AlertTriangle} from 'lucide-react';
import WorkspaceCard from './WorkspaceCard';
import WorkspaceAgents from './WorkspaceAgents';
import DraftActions from './DraftActions';
import ReplyComposer from './ReplyComposer';
import LiveResearchProgress from './LiveResearchProgress';
import {cleanDraft} from '../lib/publishable-text.mjs';
import {normalizeMarket,marketStorageSuffix} from '../lib/target-market.mjs';
import ResearchEvidenceSummary from './ResearchEvidenceSummary';
import CompetitorDiscovery from './CompetitorDiscovery';
import type {Report} from '../lib/research-types';
type Chat={role:'user'|'assistant';text:string};
const documents=['Product information','Product strategy','Marketing direction','Content strategy','Content structure','Competitor analysis'];
function documentText(report:Report,name:string){
 if(name==='Product information')return `${report.brand.name}\n\n${report.brand.summary}\n\nAudience\n${report.brand.audience}\n\nPricing\n${report.brand.pricing}\n\nStrengths\n${report.brand.strengths.join('\n')}`;
 if(name==='Competitor analysis'&&report.discovery?.competitors.length)return report.discovery.competitors.map(c=>`${c.name} · ${c.fit}\n${c.reason}\nDifference: ${c.difference}\nSource: ${c.url}`).join('\n\n');
 if(name==='Competitor analysis')return report.competitor?`${report.competitor.name}\n\n${report.competitor.summary}\n\nAudience: ${report.competitor.audience}\nPricing: ${report.competitor.pricing}\n\n${report.competitor.strengths.join('\n')}\n\nComparison is based on the reviewed homepage; market positioning needs validation.`:'No competitor was supplied. Add one to your research to compare its homepage and positioning.';
 return report.strategy.filter(s=>s.area.toLowerCase()===name.toLowerCase()).map(s=>`${s.title}\n${s.priority} · ${s.basis}\n\n${s.why}\n\nWhat to do\n${s.actions.map((a,i)=>`${i+1}. ${a}`).join('\n')}\n\nMeasure: ${s.measure}\nSources: ${s.sourceIds.join(', ')}`).join('\n\n———\n\n');
}
export default function CmoWorkspace(){
 const started=useRef(false),storageKey=useRef(''),columnsRef=useRef<HTMLDivElement>(null);
 const [widths,setWidths]=useState([20,34,24,22]),[collapsed,setCollapsed]=useState<number[]>([]);
 function resize(index:number,delta:number){setWidths(current=>{const next=[...current];const change=Math.max(10-current[index],Math.min(current[index+1]-10,delta));next[index]+=change;next[index+1]-=change;return next;})}
 function divider(index:number){return <div className="cw-resizer" role="separator" tabIndex={0} aria-label={'Resize panel '+(index+1)} aria-orientation="vertical" aria-valuenow={Math.round(widths[index])} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();resize(index,e.key==='ArrowLeft'?-2:2)}}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.dataset.x=String(e.clientX)}} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const previous=Number(e.currentTarget.dataset.x);resize(index,(e.clientX-previous)/(columnsRef.current?.clientWidth||1)*100);e.currentTarget.dataset.x=String(e.clientX)}}/>}
 function panelToggle(index:number,label:string){return <button className="cw-panel-toggle" aria-label={(collapsed.includes(index)?'Show ':'Collapse ')+label} aria-expanded={!collapsed.includes(index)} onClick={()=>setCollapsed(current=>current.includes(index)?current.filter(n=>n!==index):[...current,index])}>{collapsed.includes(index)?'›':'‹'}</button>}
 const [region,setRegion]=useState('Global');
 const [url,setUrl]=useState(''),[competitor,setCompetitor]=useState(''),[report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[view,setView]=useState('Overview'),[notes,setNotes]=useState<Record<string,string>>({}),[approved,setApproved]=useState<number[]>([]),[chat,setChat]=useState<Chat[]>([]),[question,setQuestion]=useState(''),[chatBusy,setChatBusy]=useState(false),[chatError,setChatError]=useState(''),[copied,setCopied]=useState(-1),[saveStatus,setSaveStatus]=useState('Local workspace');
 async function research(brandUrl:string,other:string,market=region){setBusy(true);setError('');try{const response=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({brandUrl,competitorUrl:other,region:market})});const data=await response.json() as Report & {error?:string};if(!response.ok)throw Error(data.error||'Research failed');setReport(data);setApproved([]);}catch(e){setError(e instanceof Error?e.message:'Could not connect.')}finally{setBusy(false)}}
 useEffect(()=>{if(started.current)return;started.current=true;const params=new URLSearchParams(window.location.search);const u=params.get('url')||'',c=params.get('competitor')||'';const market=normalizeMarket(params.get('region'));setRegion(market);setUrl(u);setCompetitor(c);storageKey.current='pinkiri-workspace-v1:'+u+':'+c+marketStorageSuffix(market);if(!u){setError('Start with a website to create your workspace.');return;}try{const saved=localStorage.getItem(storageKey.current);if(saved){const d=JSON.parse(saved);if(d.report?.brand&&Array.isArray(d.report.strategy)&&Array.isArray(d.report.sources)){setReport(d.report);setNotes(d.notes||{});setApproved(d.approved||[]);setChat(d.chat||[]);return;}}}catch{}void research(u,c,market);},[]);
 useEffect(()=>{if(!report||!storageKey.current)return;try{localStorage.setItem(storageKey.current,JSON.stringify({report,notes,approved,chat}));setSaveStatus('Saved on this device');}catch{setSaveStatus('Storage full — download your workspace');}},[report,notes,approved,chat]);
 async function askPrompt(promptText:string){if(!promptText.trim()||!report||chatBusy)return;const q=promptText.trim();setQuestion('');setChatBusy(true);setChatError('');const history=chat.slice(-6);setChat(c=>[...c,{role:'user',text:q}]);try{const context=JSON.stringify({targetMarket:report.targetMarket||region,brand:report.brand,competitor:report.competitor,discoveredCompetitors:report.discovery?.competitors,researchPlan:report.researchPlan,customerPainPoints:report.customerPainPoints,competitorTeardown:report.competitorTeardown,strategy:report.strategy,signals:report.signals,unknowns:report.unknowns,drafts:report.drafts,documents:Object.fromEntries(Object.entries(notes).map(([key,value])=>[key,value.slice(0,3500)])),sources:report.sources.map(s=>({id:s.id,url:s.url,title:s.title,content:s.content.slice(0,2200)}))}).slice(0,60000);const response=await fetch('/api/cmo-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,context,history})});const d=await response.json() as {answer:string;error?:string};if(!response.ok)throw Error(d.error||'Chat failed.');setChat(current=>[...current,{role:'assistant',text:d.answer}]);}catch(e){setChatError(e instanceof Error?e.message:'Chat failed');setQuestion(q);}finally{setChatBusy(false)}}
 async function ask(e:React.FormEvent){e.preventDefault();await askPrompt(question);}
 function download(){const file=URL.createObjectURL(new Blob([JSON.stringify({report,notes,approved,chat},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=file;a.download='pinkiri-workspace.json';a.click();setTimeout(()=>URL.revokeObjectURL(file),1000)}
 function exportCalendarIcs(){if(!report?.calendar?.length)return;const now=new Date();const pad=(n:number)=>String(n).padStart(2,'0');const fmt=(d:Date)=>`${d.getUTCFullYear()}${pad(d.getUTCMonth()+1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}Z`;const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Pinkiri AI CMO//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH',`X-WR-CALNAME:Pinkiri Marketing - ${report.brand.name}`];report.calendar.forEach((item,idx)=>{const start=new Date(Date.now()+(idx+1)*86400000);start.setUTCHours(9,0,0,0);const end=new Date(start.getTime()+1800000);lines.push('BEGIN:VEVENT',`UID:pinkiri-${report.createdAt}-${idx}@pinkiri.ai`,`DTSTAMP:${fmt(now)}`,`DTSTART:${fmt(start)}`,`DTEND:${fmt(end)}`,`SUMMARY:[${item.channel}] ${item.topic.replace(/,/g,'\\,')}`,`DESCRIPTION:Goal: ${item.goal.replace(/,/g,'\\,')} | Format: ${item.format||'Post'}\\nDay: ${item.day}`,'STATUS:CONFIRMED','END:VEVENT');});lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pinkiri-${report.brand.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-calendar.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 const sourceButtons=(ids:number[])=> <div className="cw-citations">{ids.map(id=><button key={id} onClick={()=>{setView('Evidence');setTimeout(()=>document.getElementById('cw-source-'+id)?.scrollIntoView({behavior:'smooth'}),50)}}>Source {id} ↗</button>)}</div>;
 function chatContent(text:string){
  const lines=text.split('\n');
  return lines.map((line,i)=>{
   const probeMatch=line.match(/^-\s*\[?(.*?)\]?$/);
   const isProbeSection=line.includes('Suggested Probes:')||line.includes('💡');
   if(isProbeSection)return <p key={i} className="cw-chat-probe-title"><strong>{line}</strong></p>;
   if(line.startsWith('- ')&&line.length>10&&line.endsWith('?')){
     const q=line.replace(/^[-\*\s]+\[?/, '').replace(/\]?$/, '').trim();
     return <div key={i} className="cw-chat-probe-btn-wrap"><button type="button" className="cw-probe-chip" onClick={()=>askPrompt(q)}><Sparkles size={11}/> {q}</button></div>;
   }
   return <p key={i}>{line.replace(/^#{1,6}\s+/,'').split(/(\*\*.*?\*\*|\[Source \d+[^\]]*\])/g).map((part,j)=>{const citation=part.match(/^\[Source (\d+)/);if(citation&&report?.sources.some(s=>s.id===Number(citation[1])))return <button className="cw-chat-citation" key={j} onClick={()=>{setView('Evidence');setTimeout(()=>document.getElementById('cw-source-'+citation[1])?.scrollIntoView({behavior:'smooth'}),50)}}>{part}</button>;return part.startsWith('**')?<strong key={j}>{part.slice(2,-2)}</strong>:part;})}</p>;
  });
 }
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('pinkiri-panel-layout')||'null');if(d?.widths?.length===4&&d.widths.every((n:unknown)=>typeof n==='number'&&n>=10&&n<=70)){setWidths(d.widths);setCollapsed(d.collapsed||[])}}catch{}},[]);
 function saveLayout(){try{localStorage.setItem('pinkiri-panel-layout',JSON.stringify({widths,collapsed}))}catch{}}
 const profile=report?.brand;
 return <div className="cmo-workspace"><div className="cw-top"><a href="/" className="cw-brand"><img src="/pinkiri-logo.svg" alt=""/>Pinkiri</a><span className="cw-divider"/><span>{profile?.name||'New workspace'}</span><span className="cw-top-status"><i/>{busy?'Research in progress':report?saveStatus:'Your marketing workspace'}</span><button className="cw-layout-save" onClick={saveLayout}>Save layout</button><button onClick={()=>{setWidths([20,34,24,22]);setCollapsed([])}}>Reset layout</button><a href="/" className="cw-home"><ArrowLeft size={14}/> Change website</a>{report&&<button onClick={download}><Download size={14}/> Export</button>}</div>
 <div className="cw-columns cw-adjustable" ref={columnsRef} style={{gridTemplateColumns:widths.map((n,i)=>`minmax(0, ${collapsed.includes(i)?3:n}fr)`).join(" 5px ")}}><aside className={"cw-context"+(collapsed.includes(0)?" cw-panel-collapsed":"")}><div className="cw-panel-label"><FileText size={14}/> Context{panelToggle(0,"Context")}</div><div className="cw-context-body"><div className="cw-product-icon">{profile?.name?.[0]||'P'}</div><h2>{profile?.name||'Getting to know your brand'}</h2><p className="cw-url">{url}</p><p className="cw-small">Target market: {report?.targetMarket||region} · Search focus, not verified author location.</p>{profile?<><label className="cw-label" htmlFor="brand-context">Brand brief <PenLine size={12}/></label><textarea id="brand-context" value={notes.brief??profile.summary} onChange={e=>setNotes({...notes,brief:e.target.value})}/><span className="cw-small">Editable context for your CMO</span></>:<p>Your product, audience and positioning will appear here.</p>}<div className="cw-section-title">DOCUMENTS <span>{report?documents.length:'—'}</span></div>{documents.map(name=><button key={name} disabled={!report} className={'cw-doc '+(view===name?'active':'')} onClick={()=>setView(name)}><FileText size={14}/>{name}<span>›</span></button>)}<div className="cw-section-title">COMPETITORS</div>{report&&<CompetitorDiscovery report={report} url={url} onChange={discovery=>setReport(current=>current?{...current,discovery}:current)}/>}<p>{report?.competitor?.name||'Optional: add a specific competitor'}</p><form className="cw-competitor" onSubmit={e=>{e.preventDefault();window.location.assign('/workspace?'+new URLSearchParams({url,competitor,region}).toString())}}><input aria-label="Competitor URL" placeholder="competitor.com" value={competitor} onChange={e=>setCompetitor(e.target.value)}/><button disabled={busy||!competitor.trim()}>Compare <ArrowUpRight size={12}/></button></form><p className="cw-small">Updating research creates a separate workspace for this comparison.</p></div><div className="cw-context-foot">Your CMO starts here. Keep your context up to date.</div></aside>
 {divider(0)}<main className={"cw-main"+(collapsed.includes(1)?" cw-panel-collapsed":"")}><div className="cw-panel-label"><Activity size={14}/> Intelligence <span className="cw-live-dot"/>{panelToggle(1,"Intelligence")}</div><nav className="cw-nav" aria-label="Workspace views">{['Overview','Pain Points','Competitors','Listening','Evidence'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v}</button>)}</nav>
 {busy&&<LiveResearchProgress url={url} region={region} competitor={competitor} />}
 {error&&<div className="cw-notice" role="alert"><p>{error}</p>{url?<button disabled={busy} onClick={()=>research(url,competitor)}>Retry research</button>:<a href="/">Enter your website →</a>}</div>}
 {!busy&&report&&<div className="cw-main-content">{(!report.customerPainPoints?.length || !report.competitorTeardown?.length)&&<div className="cw-notice"><strong>Update this workspace with Deep Customer & Competitor Intelligence</strong><p>Run a fresh research pass to extract granular customer emotional pain points, competitor winning formats, vulnerabilities, and counter-positioning teardowns.</p><button disabled={busy} onClick={()=>research(url,competitor)}>Run Expanded Research</button></div>}<div className="cw-view-title"><div><span className="cw-label">YOUR AI CMO</span><h1>{view==='Overview'?'Your next chapter of growth.':view}</h1></div><div style={{display:'flex',alignItems:'center',gap:'10px'}}><button disabled={busy} onClick={()=>research(url,competitor)} style={{fontSize:'11px',padding:'4px 10px',background:'var(--cw-card)',border:'1px solid var(--cw-line)',cursor:'pointer'}}>Re-run Research</button><span className="cw-date">{new Date(report.createdAt).toLocaleDateString()}</span></div></div>
 {view==='Overview'&&<><ResearchEvidenceSummary report={report}/>{report.researchPlan&&<WorkspaceCard title="Customer jobs we researched"><p>Topics extracted from your website, then searched in public social discussions. A homepage pain point is a research hypothesis until supported by conversations.</p>{report.researchPlan.topics.map((t,i)=><details key={i}><summary>{t.keyword}</summary><p>{t.painPoint}</p><p>Homepage basis: {t.homepageEvidence}</p><p>Suggested question: {t.query}. Executed platform searches are listed under Listening.</p></details>)}</WorkspaceCard>}<div className="cw-stats"><div><span>Social pages</span><strong>{report.sources.filter(s=>s.kind==='social').length}</strong></div><div><span>Customer pain points</span><strong>{report.customerPainPoints?.length||report.signals.length}</strong></div><div><span>Competitors analyzed</span><strong>{report.competitorTeardown?.length||report.discovery?.competitors.length||1}</strong></div><div><span>Drafts ready</span><strong>{report.drafts.length}</strong></div></div><h3>Your priorities</h3>{report.strategy.filter(s=>s.priority==='Now').map((s,i)=><WorkspaceCard key={i} title={s.title}><div className="cw-card-kicker">{s.area} <span>{s.basis}</span></div><h3>{s.title}</h3><p>{s.why}</p><ol>{s.actions.map((a,j)=><li key={j}>{a}</li>)}</ol><p className="cw-measure">Measure: {s.measure}</p>{sourceButtons(s.sourceIds)}</WorkspaceCard>)}<div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:'24px'}}><h3>First-week content plan</h3><button onClick={exportCalendarIcs} style={{display:'inline-flex',alignItems:'center',gap:'6px',fontSize:'12px',padding:'6px 12px',borderRadius:'6px',background:'var(--accent-tint,#2563eb1a)',color:'var(--accent,#2563eb)',border:'1px solid var(--accent,#2563eb)',cursor:'pointer',fontWeight:600}}><CalendarIcon size={13}/> Export Calendar (.ics)</button></div>{report.calendar.map((day,i)=><div className="cw-calendar" key={i}><b>{day.day}</b><div><span style={{display:'inline-block',marginBottom:'4px'}}>{day.channel} {day.time?`· ${day.time}`:''} {day.format?`· ${day.format}`:''}</span><h4>{day.topic}</h4><p>{day.goal}</p></div></div>)}<p className="cw-small">Click "Export Calendar (.ics)" to sync scheduled campaigns straight to Apple Calendar, Google Calendar, or Outlook.</p></>}
 {view==='Pain Points'&&<><h3>Deep Customer Pain Points & Emotional Triggers</h3><p className="cw-small">Extracted directly from user complaints, community forums, reviews, and creator videos.</p>{(!report.customerPainPoints||!report.customerPainPoints.length)&&<div className="cw-card"><p>No categorized pain points extracted in this run. View the <strong>Listening</strong> tab for raw signals or re-run research.</p></div>}{report.customerPainPoints?.map((p,i)=><WorkspaceCard key={i} title={p.category}><div className="cw-card-kicker">{p.category} <span style={{color:p.severity==='High'?'#ef4444':p.severity==='Medium'?'#f59e0b':'#10b981',fontWeight:700}}>{p.severity} Severity</span></div><h3>{p.painPoint}</h3><p><strong>Emotional Trigger:</strong> {p.emotionalTrigger}</p><p><strong>Frequency:</strong> {p.frequency}</p><p><strong>Competitor Vulnerability:</strong> {p.competitorVulnerability}</p>{p.quote&&<blockquote>“{p.quote}”</blockquote>}{p.sourceId?sourceButtons([p.sourceId]):null}</WorkspaceCard>)}</>}
 {view==='Competitors'&&<><h3>Competitor Social & Messaging Teardowns</h3><p className="cw-small">Balanced analysis of both what competitors do exceptionally well and where their vulnerabilities lie.</p>{(!report.competitorTeardown||!report.competitorTeardown.length)&&report.discovery?.competitors.map((c,i)=><WorkspaceCard key={i} title={c.name}><div className="cw-card-kicker">Competitor · {c.fit}</div><h3>{c.name}</h3><p>{c.reason}</p><p><strong>Difference:</strong> {c.difference}</p><a href={c.url} target="_blank" rel="noreferrer">Visit website <ArrowUpRight size={12}/></a></WorkspaceCard>)}{report.competitorTeardown?.map((c,i)=><WorkspaceCard key={i} title={c.name}><div className="cw-card-kicker">Competitor Teardown</div><h3>{c.name}</h3><div style={{marginTop:'10px',marginBottom:'10px'}}><strong><ThumbsUp size={13} style={{display:'inline',marginRight:'4px',color:'#10b981'}}/> What Works Well (Why Users Choose Them):</strong><ul>{c.whatWorksWell.map((w,j)=><li key={j}>{w}</li>)}</ul></div><div style={{marginTop:'10px',marginBottom:'10px'}}><strong>Top Formats & Hooks:</strong><ul>{c.topFormats.map((f,j)=><li key={j}>{f}</li>)}</ul></div><div style={{marginTop:'10px',marginBottom:'10px'}}><strong>Core Value Props & Messaging:</strong><ul>{c.messagingHooks.map((h,j)=><li key={j}>{h}</li>)}</ul></div><div style={{marginTop:'10px',marginBottom:'10px'}}><strong><AlertTriangle size={13} style={{display:'inline',marginRight:'4px',color:'#ef4444'}}/> Customer Complaints & Vulnerabilities:</strong><ul>{c.vulnerabilities.map((v,j)=><li key={j}>{v}</li>)}</ul></div><div style={{marginTop:'12px',padding:'10px',background:'var(--accent-tint,#2563eb12)',borderRadius:'6px'}}><strong>Counter-Positioning Angle for Your Brand:</strong><p style={{marginTop:'4px',marginBottom:0}}>{c.counterPositioningAngle}</p></div></WorkspaceCard>)}</>}
 {documents.includes(view)&&<><p className="cw-small">Edit your working document. Changes are saved on this device and included in CMO chat context.</p><textarea className="cw-document-editor" aria-label={'Edit '+view} value={notes[view]??documentText(report,view)} onChange={e=>setNotes({...notes,[view]:e.target.value.slice(0,12000)})}/><h3>Research references</h3>{sourceButtons([...new Set(report.strategy.filter(s=>s.area.toLowerCase()===view.toLowerCase()).flatMap(s=>s.sourceIds))])}{view==='Product information'&&sourceButtons([1])}</>}
 {view==='Listening'&&<><div className="cw-notice">A snapshot of public indexed discussions. Missing or inaccessible posts are not evidence of missing demand.</div>{!report.signals.length&&<div className="cw-card"><h3>No verified relevant conversations in this run</h3><p>Strategy remains provisional. Validate it with customer interviews and further research before treating it as market demand.</p></div>}{report.signals.map((s,i)=><WorkspaceCard key={i} title={s.theme}><div className="cw-card-kicker">{s.scope} · {s.speaker}<span>{s.sentiment}</span></div><h3>{s.theme}</h3><p>{s.finding}</p>{s.quote&&<blockquote>“{s.quote}”</blockquote>}{sourceButtons([s.sourceId])}</WorkspaceCard>)}<h3>Platform coverage</h3>{report.coverage.filter(c=>c.platform!=='Reddit').map((c,i)=><WorkspaceCard key={i} title={c.platform+" coverage"}><strong>{c.platform} · {c.scope}</strong><p>{c.status}</p><span className="cw-small">{c.found} results · {c.read} pages read · Past-month search filter</span><details><summary>Search details</summary><p>{c.query}</p><p>{new Date(c.searchedAt).toLocaleString()}</p></details></WorkspaceCard>)}</>}
 {view==='Evidence'&&<><h3>What we couldn’t establish</h3><ul>{report.unknowns.map((s,i)=><li key={i}>{s}</li>)}</ul>{report.sources.map(s=><WorkspaceCard key={s.id} title={s.title} id={'cw-source-'+s.id}><span className="cw-label">SOURCE {s.id} · {s.platform}</span><h3>{s.title}</h3><a href={s.url} target="_blank" rel="noreferrer">Open original <ArrowUpRight size={12}/></a><p>Published: {s.publishedAt||'Unknown'}<br/>Read: {new Date(s.retrievedAt).toLocaleString()}</p><details><summary>View source text</summary><pre>{s.content}</pre></details></WorkspaceCard>)}</>}
 </div>}</main>
 {divider(1)}<section className={"cw-feed"+(collapsed.includes(2)?" cw-panel-collapsed":"")}><div className="cw-panel-label"><Activity size={14}/> Drafts feed <span className="cw-count">{report?.drafts.length||0}</span>{panelToggle(2,"Drafts and agents")}</div><div className="cw-feed-body"><details className="cw-drafts-group"><summary>Drafts to review <span className="cw-count">{report?.drafts.length||0}</span></summary><p className="cw-small">Expand a draft to edit, copy, or mark it reviewed.</p>{!report&&<div className="cw-empty"><FileText size={28}/><p>Content drafts arrive here once your research is complete.</p></div>}{report?.drafts.map((d,i)=><WorkspaceCard key={i} title={d.title}><div className="cw-card-kicker">{d.format}<span>{approved.includes(i)?'Reviewed':'Draft'}</span></div><h3>{d.title}</h3><span className="cw-small">{d.basis}</span><textarea aria-label={'Edit '+d.format+' draft'} value={cleanDraft(d.content)} onChange={e=>{setReport({...report,drafts:report.drafts.map((x,n)=>n===i?{...x,content:e.target.value}:x)});setApproved(approved.filter(n=>n!==i));}}/>{sourceButtons(d.sourceIds)}<div className="cw-draft-actions"><button onClick={()=>setApproved(approved.includes(i)?approved.filter(n=>n!==i):[...approved,i])}><Check size={12}/>{approved.includes(i)?'Reviewed':'Mark reviewed'}</button></div><DraftActions value={d.content} onChange={content=>{setReport({...report,drafts:report.drafts.map((x,n)=>n===i?{...x,content}:x)});setApproved(approved.filter(n=>n!==i));}} report={report} sourceIds={d.sourceIds} storageKey={storageKey.current+':'+report.createdAt+':draft:'+i}/></WorkspaceCard>)}</details>{report&&<WorkspaceAgents key={report.createdAt} report={report} notes={notes} workspaceKey={storageKey.current+':'+report.createdAt}/>}{report&&<ReplyComposer key={'replies:'+report.createdAt} report={report} storageKey={storageKey.current+':'+report.createdAt+':replies'}/>}<p className="cw-small">You control what gets published. These drafts are not posted automatically.</p></div></section>
 {divider(2)}<aside className={"cw-chat"+(collapsed.includes(3)?" cw-panel-collapsed":"")}><div className="cw-chat-brand"><div className="cw-orb"><MessageSquare size={19}/></div><div><strong>Your CMO</strong><p>Grounded in your workspace</p></div><span className="cw-live-dot"/></div><div className="cw-panel-label"><MessageSquare size={14}/> Chat{panelToggle(3,"Chat")}</div><div className="cw-chat-messages" aria-live="polite">{!chat.length&&<div className="cw-chat-welcome"><div className="cw-orb"><Search size={24}/></div><h2>Let’s find your next move.</h2><p>Ask about your audience, strategy or drafts. I’ll work from the research and flag what still needs validation.</p>{['What are the top emotional pain points of my audience?','What are Flutterwave and Paystack’s biggest vulnerabilities?','Write a high-converting TikTok script targeting card decline anxiety'].map(q=><button key={q} disabled={!report} onClick={()=>askPrompt(q)}>{q}<ArrowUpRight size={13}/></button>)}</div>}{chat.map((m,i)=><div key={i} className={'cw-message '+m.role}><span>{m.role==='user'?'You':'Pinkiri CMO'}</span><div>{chatContent(m.text)}</div></div>)}{chatBusy&&<p role="status"><LoaderCircle size={14} className="spin"/> Thinking with your research…</p>}{chatError&&<p className="cw-notice" role="alert">{chatError}</p>}</div><form className="cw-chat-form" onSubmit={ask}><textarea aria-label="Ask your CMO" maxLength={2000} placeholder={report?'Ask your CMO anything…':'Waiting for your research…'} value={question} disabled={!report||chatBusy} onChange={e=>setQuestion(e.target.value)}/><div><span>Research-aware · Gemini</span><button aria-label="Send message" disabled={!report||chatBusy||!question.trim()}><Send size={16}/></button></div></form></aside></div></div>
}

