"use client";
import {useState,useEffect,useRef} from 'react';
import {LoaderCircle,ExternalLink,Copy,Check,Download} from 'lucide-react';
import type {Report} from '../lib/research-types';
const tabs=['Overview','Listening','Strategy','Content','Evidence'] as const;
export default function ResearchWorkspace({initialUrl='',initialCompetitor='',onBusyChange}:{initialUrl?:string;initialCompetitor?:string;embedded?:boolean;onBusyChange?:(busy:boolean)=>void}){
 const started=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[report,setReport]=useState<Report|null>(null),[copied,setCopied]=useState(-1),[tab,setTab]=useState<typeof tabs[number]>('Overview');
 async function run(){setBusy(true);onBusyChange?.(true);setError('');try{const r=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({brandUrl:initialUrl,competitorUrl:initialCompetitor})});const d=await r.json() as Report & {error?:string};if(!r.ok)throw Error(d.error||'Research failed.');setReport(d)}catch(e){setError(e instanceof Error?e.message:'Could not connect.')}finally{setBusy(false);onBusyChange?.(false)}}
 useEffect(()=>{if(initialUrl&&!started.current){started.current=true;void run();}},[]);
 function citations(ids:number[]){return <div className="evidence-links">{ids.map(id=><button key={id} onClick={()=>{setTab('Evidence');setTimeout(()=>document.getElementById('source-'+id)?.scrollIntoView({behavior:'smooth'}),50)}}>Source {id} ↗</button>)}</div>}
 function download(){if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pinkiri-research.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="site"><main className="research-workspace"><p className="eyebrow">YOUR AI CMO · RESEARCH WORKSPACE</p>
 {busy&&<div className="research-progress" role="status"><LoaderCircle className="spin"/><h2>From brand context to customer evidence.</h2><p>Reading your website, searching public social discussions, and building your strategy. This can take several minutes.</p><small>Searches cover the past month in the public index. Up to 5 searches and 6 social page reads; collected evidence is cached for one hour.</small></div>}
 {error&&<div role="alert"><p className="error">{error}</p><button className="pill" disabled={busy} onClick={run}>Retry research</button></div>}
 {report&&<section className="research-results"><div className="research-heading"><div><small>{report.cached?'CACHED RESEARCH':'RESEARCH SNAPSHOT'} · {new Date(report.createdAt).toLocaleString()}</small><h2>{report.brand.name}’s next chapter of growth.</h2></div><button className="pill" onClick={download}><Download size={15}/> Save report data</button></div>
 <p>Public indexed discussions, researched on demand. This is a limited sample, not a continuous live feed. Check publication dates and source context before acting.</p>
 <div className="research-tabs" role="tablist" aria-label="Research sections">{tabs.map(t=><button key={t} role="tab" id={'tab-'+t} aria-controls="research-panel" aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 <div role="tabpanel" id="research-panel" aria-labelledby={'tab-'+tab}>
 {tab==='Overview'&&<><div className="research-metrics"><article><small>Social pages read</small><h2>{report.sources.filter(s=>s.kind==='social').length}</h2></article><article><small>Relevant findings</small><h2>{report.signals.length}</h2></article><article><small>Strategy actions</small><h2>{report.strategy.reduce((n,s)=>n+s.actions.length,0)}</h2></article></div><div className="profile-grid">{[report.brand,report.competitor].filter(p=>p!==null).map((p,i)=><article key={i}><small>{i?'COMPETITOR CONTEXT':'BRAND CONTEXT'}</small><h2>{p.name}</h2><p>{p.summary}</p><h3>Audience</h3><p>{p.audience}</p><h3>Pricing</h3><p>{p.pricing}</p><ul>{p.strengths.map(s=><li key={s}>{s}</li>)}</ul></article>)}</div><h2>Your next moves</h2>{report.strategy.filter(s=>s.priority==='Now').map((s,i)=><article key={i}><small>{s.area} · {s.basis}</small><h3>{s.title}</h3><p>{s.actions[0]}</p>{citations(s.sourceIds)}</article>)}<button className="pill" onClick={()=>setTab('Strategy')}>Review the full strategy →</button></>}
 {tab==='Listening'&&<><h2>What people are saying</h2><p>Product mentions and category needs are separated below. Creator posts are labeled and should not be read as customer feedback.</p>{report.signals.length===0&&<article><h3>No verified relevant conversation found in this run</h3><p>We could not establish customer sentiment from the pages available. Recommendations are provisional homepage hypotheses, with validation steps.</p></article>}{report.signals.map((s,i)=>{const source=report.sources.find(x=>x.id===s.sourceId);return <article key={i}><small>{source?.platform} · {s.scope} discussion · {s.speaker} · {s.sentiment}</small><h3>{s.theme}</h3><p>{s.finding}</p>{s.quote&&<blockquote>“{s.quote}”</blockquote>}<p>Published: {source?.publishedAt||'Unknown'} · Retrieved: {source?new Date(source.retrievedAt).toLocaleString():''}</p>{citations([s.sourceId])}</article>})}<h2>Platform coverage</h2>{report.coverage.filter(c=>c.platform!=='Reddit').map((c,i)=><article key={i}><h3>{c.platform} · {c.scope} search</h3><p>{c.status}. {c.found} post results found; {c.read} new pages read.</p><small>{c.window}</small><details><summary>Search details</summary><p>{c.query}</p><p>Searched {new Date(c.searchedAt).toLocaleString()}</p>{c.urls.map(u=><p key={u}><a className="source-link" href={u} target="_blank" rel="noreferrer">{u}</a></p>)}</details></article>)}</>}
 {tab==='Strategy'&&<><h2>What to do, and why</h2><p>Recommendations are experiments, not guaranteed outcomes. Each one states its evidence and how to measure progress.</p>{report.strategy.map((s,i)=><article key={i}><small>{s.area} · {s.priority} · {s.basis}</small><h3>{s.title}</h3><p>{s.why}</p><h3>How to put it into practice</h3><ol>{s.actions.map((a,n)=><li key={n}>{a}</li>)}</ol><h3>Measure</h3><p>{s.measure}</p>{citations(s.sourceIds)}</article>)}</>}
 {tab==='Content'&&<><h2>Your first week</h2><p>A suggested publishing plan. Nothing is scheduled or posted automatically.</p><div className="calendar-grid">{report.calendar.map((c,i)=><article key={i}><small>{c.day} · {c.channel}</small><h3>{c.topic}</h3><p>{c.goal}</p><small>Supports: {report.strategy[c.strategyIndex]?.title}</small></article>)}</div><h2>Your draft studio</h2>{report.drafts.map((d,i)=><article key={i}><small>{d.format} · {d.basis}</small><h3>{d.title}</h3>{citations(d.sourceIds)}<textarea aria-label={'Edit '+d.format} value={d.content} onChange={e=>setReport({...report,drafts:report.drafts.map((x,n)=>n===i?{...x,content:e.target.value}:x)})}/><button className="pill" onClick={async()=>{try{await navigator.clipboard.writeText(d.content);setCopied(i)}catch{setError('Clipboard unavailable. Select and copy the draft text manually.')}}}>{copied===i?<Check size={15}/>:<Copy size={15}/>} {copied===i?'Copied':'Copy draft'}</button></article>)}</>}
 {tab==='Evidence'&&<><h2>Limits and unanswered questions</h2><article><ul>{report.unknowns.map((u,i)=><li key={i}>{u}</li>)}</ul><p>Public search indexing and page access limit coverage. A page retrieval time is not its publication date. Private posts, missing comments and inaccessible content were not analyzed.</p></article><h2>Read the evidence</h2>{report.sources.map(s=><article key={s.id} id={'source-'+s.id}><small>{s.kind} · {s.platform}</small><h3>Source {s.id}: {s.title}</h3><a className="source-link" href={s.url} target="_blank" rel="noreferrer">{s.url}<ExternalLink size={14}/></a><p>Published: {s.publishedAt||'Unknown'}<br/>Retrieved {new Date(s.retrievedAt).toLocaleString()}</p><details><summary>Read the source text used</summary><pre>{s.content}</pre></details></article>)}</>}
 </div></section>}</main></div>
}
