"use client";
import {useEffect,useRef,useState} from 'react';
import {Bot,LoaderCircle,Copy} from 'lucide-react';
import WorkspaceCard from './WorkspaceCard';
import DraftActions from './DraftActions';
import {cleanDraft} from '../lib/publishable-text.mjs';
import type {Report} from '../lib/research-types';
const agents=[
 ['Influencer','Find a creator profile and outreach direction','Create a specific influencer campaign brief: target creator criteria, vetting checklist, outreach draft and measurement. Do not invent creator names, audience sizes or actual outreach.'],
 ['SEO','Plan useful content for search','Create three SEO article briefs grounded in the product and research: intent, title, outline, CTA. Keywords are hypotheses; do not invent search volume or ranking data.'],
 ['GEO','Make your product easier to understand','Prepare a factual product FAQ and a plan to improve clear machine-readable product information. Do not claim measured AI citation gaps.'],
 ['X','Write a focused thread','Write a numbered 5-post X thread grounded in the product and customer evidence. Label any assumptions and avoid unsupported claims.'],
 ['Articles','Write a complete evidence-led article','Write a complete concise article of 250–300 words, with a title, useful body, and CTA based on the most useful evidenced strategy opportunity. Cite evidence and label hypotheses.'],
 ['LinkedIn','Create a professional point of view','Draft a LinkedIn post and two alternative hooks with a specific audience and CTA, grounded in workspace research.'],
 ['UGC video','Build a scene-by-scene video brief','Create a 30-second video script with timing, scenes, on-screen text, spoken audio and CTA. Do not invent testimonials or product demonstrations.']
];
export default function WorkspaceAgents({report,notes,workspaceKey}:{report:Report;notes:Record<string,string>;workspaceKey:string}){
 const active=useRef(false);const [batch,setBatch]=useState(false);
 const [outputs,setOutputs]=useState<Record<string,string>>({}),[running,setRunning]=useState(''),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[copied,setCopied]=useState('');
 useEffect(()=>{try{setOutputs(JSON.parse(localStorage.getItem(workspaceKey+':agents')||'{}'))}catch{}setLoaded(true)},[workspaceKey]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(workspaceKey+':agents',JSON.stringify(outputs))}catch{setError('Could not save agent outputs on this device. Copy the output to keep it.')}},[outputs,loaded,workspaceKey]);
 async function run(name:string,instruction:string){setRunning(name);setError('');try{const r=await fetch('/api/cmo-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:instruction+' Use the customer pain-point findings and verified competitor differences to decide the angle. Explicitly distinguish observed needs from hypotheses. Return the actual deliverable, not a promise to work later. Explain the core business value and customer problem behind your angle. Treat recent posts as a snapshot; do not claim growing trends without time-series evidence. Cite supporting source IDs and state where evidence is missing. Use document edits as user context. Do not claim to have researched, posted or contacted anyone beyond the supplied evidence.',history:[],context:JSON.stringify({targetMarket:report.targetMarket||'Global',brand:report.brand,competitors:report.discovery?.competitors,researchPlan:report.researchPlan,documents:Object.fromEntries(Object.entries(notes).map(([key,value])=>[key,value.slice(0,2500)])),strategy:report.strategy,signals:report.signals,coverage:report.coverage,unknowns:report.unknowns,sources:report.sources.map(s=>({id:s.id,url:s.url,publishedAt:s.publishedAt,retrievedAt:s.retrievedAt,content:s.content.slice(0,1000)}))}).slice(0,60000)})});const d=await r.json() as {answer:string;error?:string};if(!r.ok)throw Error(d.error||'Agent could not complete the task.');setOutputs(current=>({...current,[name]:d.answer}));return true;}catch(e){setError(e instanceof Error?e.message:'Agent failed.')}finally{setRunning('')}}
 async function runAll(){if(active.current)return;active.current=true;setBatch(true);try{for(const [name,,prompt] of agents){if(!await run(name,prompt))break;}}finally{active.current=false;setBatch(false)}}
 async function runOne(name:string,prompt:string){if(active.current)return;active.current=true;try{await run(name,prompt)}finally{active.current=false}}
 return <section className="cw-agents"><div className="cw-section-title">AGENTS <span>{agents.length} specialists · shared research</span></div><button disabled={batch||!!running} onClick={runAll}>{batch?'Running agents…':'Run all agents'}</button><p className="cw-small">Runs {agents.length} tasks in sequence using this report. Stops if a provider fails; completed work stays saved.</p>{error&&<p role="alert" className="cw-notice">{error}</p>}{agents.map(([name,description,prompt])=><WorkspaceCard key={name} title={name+' Agent · '+(running===name?'Working':outputs[name]?'Ready to review':'Ready to start')} defaultOpen={false}><p>{description}</p><span className="cw-small">Uses your workspace research. No automatic posting.</span>{outputs[name]&&<textarea aria-label={'Edit '+name+' agent output'} value={cleanDraft(outputs[name])} onChange={e=>setOutputs({...outputs,[name]:e.target.value})}/>}<div className="cw-draft-actions"><button disabled={batch||!!running} onClick={()=>runOne(name,prompt)}>{running===name?<LoaderCircle size={13} className="spin"/>:<Bot size={13}/>} {outputs[name]?'Generate another':'Run agent'}</button></div>{outputs[name]&&<DraftActions value={outputs[name]} onChange={text=>setOutputs(current=>({...current,[name]:text}))} report={report} storageKey={workspaceKey+':publish:'+name}/>}</WorkspaceCard>)}</section>
}
